version: '3.8'

services:
  pgdb:
    image: postgres:17
    environment:
      POSTGRES_DB: "cat_project"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  server:
    build:
      context: ./server
    container_name: server
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb

  client:
    build:
      context: ./client
    container_name: client
    command: "ng serve --host 0.0.0.0"
    ports:
      - "4200:4200"
    depends_on:
      - server


volumes:
  pgdbdata: null