# Generated by Django 5.1.1 on 2024-10-08 15:22

import cats.models
import cats.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('age', models.PositiveSmallIntegerField(validators=[cats.validators.check_cat_age], verbose_name='Возраст')),
                ('breed', models.CharField(max_length=128, verbose_name='Порода')),
                ('color', models.CharField(max_length=96, verbose_name='Цвет')),
                ('favorite_food', models.TextField(blank=True, null=True, verbose_name='Любимая еда')),
                ('_photo', models.ImageField(blank=True, db_column='photo', null=True, upload_to=cats.models.upload_cat_image_to, verbose_name='Фотография')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to=settings.AUTH_USER_MODEL, verbose_name='Хозяин')),
            ],
            options={
                'verbose_name': 'Кошка',
                'verbose_name_plural': 'Кошки',
                'db_table': 'Cat',
                'constraints': [models.CheckConstraint(condition=models.Q(('age__lte', 30), ('age__gte', 1), _connector='OR'), name='cat_age_between_1_and_30', violation_error_message='Возраст не может быть меньше 1 и больше 30')],
            },
        ),
    ]
