# Generated by Django 5.1.1 on 2024-10-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='favorite_food',
            field=models.TextField(blank=True, null=True, verbose_name='Любимая еда'),
        ),
    ]
