# Generated by Django 5.1.1 on 2024-10-07 17:00

import cats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_cat_favorite_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='photo',
        ),
        migrations.AddField(
            model_name='cat',
            name='_photo',
            field=models.ImageField(db_column='photo', default='', upload_to=cats.models.upload_cat_image_to, verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
