# Generated by Django 5.1.1 on 2024-10-07 17:05

import cats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_remove_cat_photo_cat__photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='_photo',
            field=models.ImageField(blank=True, db_column='photo', null=True, upload_to=cats.models.upload_cat_image_to, verbose_name='Фотография'),
        ),
    ]
